# Generated by Django 6.0.3 on 2026-03-05 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_Cliente', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=20)),
                ('data_entrada', models.DateField()),
                ('data_saida', models.DateField()),
                ('Status', models.CharField(choices=[('Pendente', 'Pendente'), ('Confirmado', 'confirmado'), ('Cancelado', 'Cancelado')], default='Pendente', max_length=20)),
            ],
        ),
    ]
