# Generated by Django 6.0.3 on 2026-03-05 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reserva',
            old_name='nome_Cliente',
            new_name='nome_cliente',
        ),
    ]
